### ISSUE TITLE
Unable to fetch room reservation list on date change

### ISSUE THREAD

**Issue by sharon698** [harpreetsingh17/OSSE_Assignment_Group_11#10]
![image](https://user-images.githubusercontent.com/49211367/146200714-84703a2f-eb29-4c25-8473-132a48117a9c.png)
![image](https://user-images.githubusercontent.com/49211367/146200802-acc6c9eb-8578-4594-87bb-ddf560482ed1.png)

**Comment by ragini-bhadani** [comment]
Fixed now
