### ISSUE TITLE
Cannot find symbol in reservationrepository

### ISSUE THREAD

**Issue by harpreetsingh17** [harpreetsingh17/OSSE_Assignment_Group_11#12]
![MicrosoftTeams-image (26)](https://user-images.githubusercontent.com/46319402/146204789-0c30d7f2-c0e8-47a0-9286-721d4c3eab05.png)

**Comment by sharon698** [comment]
Resolved via PR - https://github.com/harpreetsingh17/OSSE_Assignment_Group_11/pull/20
