### ISSUE TITLE
Unable to execute due to white label page error 

### ISSUE THREAD

**Issue by ragini-bhadani** [harpreetsingh17/OSSE_Assignment_Group_11#16]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/84861989/146374335-35846b9c-87cb-4690-ad74-6d49c5ce5e64.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/84861989/146374337-f9227363-5e32-45e4-9a89-1c00d5997bc7.png)

**Comment by harpreetsingh17** [comment]
Fixed now
