### ISSUE TITLE
On changing date page contents are not loading .

### ISSUE THREAD

**Issue by ragini-bhadani** [harpreetsingh17/OSSE_Assignment_Group_11#18]
only when we do a force reload it work
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/84861989/146377367-aa60cc41-65b0-49f4-9347-35f915bab29e.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/84861989/146377371-852b51e1-bdd5-4175-884d-c83c868df968.png)
s

**Comment by sharon698** [comment]
This issue is resolved now
